package com.stefanini.model;
// Generated 07/11/2016 12:04:54 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proprietario generated by hbm2java
 */
@Entity
public class Proprietario implements java.io.Serializable {

	private Integer cpfProprietario;
	private String nome;
	private String endereco;
	private String bairro;
	private String cidade;
	private String uf;
	private String sexo;
	private Date dtNascimento;

	public Proprietario() {
	}

	public Proprietario(String nome, String endereco, String bairro, String cidade, String uf, String sexo,
			Date dtNascimento) {
		this.nome = nome;
		this.endereco = endereco;
		this.bairro = bairro;
		this.cidade = cidade;
		this.uf = uf;
		this.sexo = sexo;
		this.dtNascimento = dtNascimento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cpfProprietario", unique = true, nullable = false)
	public Integer getCpfProprietario() {
		return this.cpfProprietario;
	}

	public void setCpfProprietario(Integer cpfProprietario) {
		this.cpfProprietario = cpfProprietario;
	}

	@Column(name = "nome", length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "endereco", length = 100)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "bairro", length = 100)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "cidade", length = 100)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "uf", length = 2)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Column(name = "sexo", length = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtNascimento", length = 10)
	public Date getDtNascimento() {
		return this.dtNascimento;
	}

	public void setDtNascimento(Date dtNascimento) {
		this.dtNascimento = dtNascimento;
	}

}
